ecommerce-master/ecommerce-master/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('api/',include('home.api_urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommerce-master/ecommerce-master/home/urls.py
from .views import HomeView,ItemDetailView,Subcategory,SearchView,signup,cart,ContactView,CartView,removecart,deletecart,contact_action
from django.urls import path
app_name = 'home'


urlpatterns = [
    path('', HomeView.as_view(),name='home'),
    path('product/<slug>', ItemDetailView.as_view(),name='product'),
    path('subcategory/<id>', Subcategory.as_view(),name='subcategory'),
    path('cart/<slug>', cart, name='cart'),
    path('removecart/<slug>', removecart, name='removecart'),
    path('deletecart/<slug>', cart, name='deletecart'),
    path('search', SearchView.as_view(), name='search'),
    path('signup',signup, name='signup'),
    path('mycart',CartView.as_view(), name='mycart'),
    path('contact',ContactView.as_view(), name='contact'),
    path('contact_action', contact_action, name='contact_action'),
]

ecommerce-master/ecommerce-master/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--content-->
<div class="content-top offer-w3agile">
	<div class="container ">
		<div class="spec ">
			<h3>My Cart</h3>
							<div class="ser-t">
					<b></b>
					<span><i></i></span>
					<b class="line"></b>
				</div>
		</div>
						<div class=" con-w3l wthree-of">
                            {% for carts in slugs %}
                            {% for item in items %}
                            {% if item.slug == carts.slug %}
							<div class="col-md-3 pro-1">
								<div class="col-m">
									<a href="#" data-toggle="modal" data-target="#myModal1" class="offer-img">
										<img src="{{carts.image}}" class="img-responsive" alt="">
										<div class="offer"><p><span>Offer</span></p></div>
									</a>
									<div class="mid-1">
										<div class="women">
											<h6><a href="single.html">{{carts.title}}</a></h6>
										</div>
										<div class="mid-2">
                                            {% if carts.discounted_price%}
											<p ><label>${{carts.price}}</label><em class="item_price">${{carts.discounted_price}}</em></p>
                                            {% else%}
                                            <p ><em class="item_price">${{carts.price}}</em></p>
                                            {% endif %}
											  <div class="block">
												<div class="starbox small ghosting"> </div>
											</div>
											<div class="clearfix"></div>
										</div>
										<div class="add">
											<a href = "" ><button class="btn btn-danger my-cart-btn my-cart-b ">+</button></a>
											<a href = "" ><button class="btn btn-danger my-cart-btn my-cart-b ">-</button></a>
											<a href = "" ><button class="btn btn-danger my-cart-btn my-cart-b ">Delete</button></a>
										</div>

									</div>
								</div>
							</div>
                            {% endif %}
                            {% endfor %}
                            {% endfor %}


							<div class="clearfix"></div>
						 </div>
					</div>
				</div>
{% endblock %}

ecommerce-master/ecommerce-master/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <!--banner-->
<div class="banner-top">
	<div class="container">
		<h3 >Contact</h3>
		<h4><a href="index.html">Home</a><label>/</label>Contact</h4>
		<div class="clearfix"> </div>
	</div>
</div>

<!-- contact -->
<div class="contact">
	<div class="container">
		<div class="spec ">
			<h3>Contact</h3>
				<div class="ser-t">
					<b></b>
					<span><i></i></span>
					<b class="line"></b>
				</div>
		</div>
		<div class=" contact-w3">	
			<div class="col-md-5 contact-right">	
				<img src="images/cac.jpg" class="img-responsive" alt="">
				<iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d2482.432383990807!2d0.028213999961443994!3d51.52362882484525!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1423469959819" style="border:0"></iframe>
			</div>
			<div class="col-md-7 contact-left">
				<h4>Contact Information</h4>
				<p> Nemo enim ipsam voluptatem quia voluptas sit aspernatur 
				aut odit aut fugit, sed quia consequuntur magni dolores eos
				qui ratione voluptatem sequi nesciunt. Neque porro quisquam 
				est, qui dolorem ipsum quia dolor sit amet, consectetur</p>
				<ul class="contact-list">
					<li> <i class="fa fa-map-marker" aria-hidden="true"></i> 756 Global Place, New York.</li>
					<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:example@mail.com">mail@example.com</a></li>
					<li> <i class="fa fa-phone" aria-hidden="true"></i>+123 2222 222</li>
				</ul>
				<div id="container">
					<!--Horizontal Tab-->
					<div id="parentHorizontalTab">
						<ul class="resp-tabs-list hor_1">
							<li><i class="fa fa-envelope" aria-hidden="true"></i></li>
							<li> <i class="fa fa-map-marker" aria-hidden="true"></i> </span></li>
							<li> <i class="fa fa-phone" aria-hidden="true"></i></li>
						</ul>
						<div class="resp-tabs-container hor_1">
							<div>
								<form action="{% url 'home:contact_action' %}" method="POST">
									{% csrf_token %}
									<input type="text" name="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
									<input type="email" name="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
									<textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
									<input type="submit" value="Submit" >
								</form>
							</div>
							<div>
								<div class="map-grid">
								<h5>Our Branches</h5>
									<ul>
										<li><i class="fa fa-arrow-right" aria-hidden="true"></i>756 Global Place, New York.</li>
										<li><i class="fa fa-arrow-right" aria-hidden="true"></i>889 diamond street, USA.</li>
										<li><i class="fa fa-arrow-right" aria-hidden="true"></i>756 global Place, New York.</li>
										<li><i class="fa fa-arrow-right" aria-hidden="true"></i>889 diamond street, USA.</li>
									</ul>
								</div>
							</div>
							<div>
								<div class="map-grid">
									<h5>Contact Me Through</h5>
									<ul>
										<li>Mobile No : +123 456 7890</li>
										<li>Office No : +123 222 2222</li>
										<li>Home No : +123 456 7890</li>
										<li>Fax No : +123 456 7890</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<!--Plug-in Initialisation-->
				<script type="text/javascript">
				$(document).ready(function() {
					//Horizontal Tab
					$('#parentHorizontalTab').easyResponsiveTabs({
						type: 'default', //Types: default, vertical, accordion
						width: 'auto', //auto or any width like 600px
						fit: true, // 100% fit in a container
						tabidentify: 'hor_1', // The tab groups identifier
						activate: function(event) { // Callback function if tab is switched
							var $tab = $(this);
							var $info = $('#nested-tabInfo');
							var $name = $('span', $info);
							$name.text($tab.text());
							$info.show();
						}
					});

					// Child Tab
					$('#ChildVerticalTab_1').easyResponsiveTabs({
						type: 'vertical',
						width: 'auto',
						fit: true,
						tabidentify: 'ver_1', // The tab groups identifier
						activetab_bg: '#fff', // background color for active tabs in this group
						inactive_bg: '#F5F5F5', // background color for inactive tabs in this group
						active_border_color: '#c1c1c1', // border color for active tabs heads in this group
						active_content_border_color: '#5AB1D0' // border color for active tabs contect in this group so that it matches the tab head border
					});

					//Vertical Tab
					$('#parentVerticalTab').easyResponsiveTabs({
						type: 'vertical', //Types: default, vertical, accordion
						width: 'auto', //auto or any width like 600px
						fit: true, // 100% fit in a container
						closed: 'accordion', // Start closed if in accordion view
						tabidentify: 'hor_1', // The tab groups identifier
						activate: function(event) { // Callback function if tab is switched
							var $tab = $(this);
							var $info = $('#nested-tabInfo2');
							var $name = $('span', $info);
							$name.text($tab.text());
							$info.show();
						}
					});
				});
			</script>
				
			</div>
			
		<div class="clearfix"></div>
	</div>
	</div>
</div>
<!-- //contact -->
{% endblock %}

ecommerce-master/ecommerce-master/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!---->
<div data-vide-bg="{% static 'video/video' %}">
    <div class="container">
		<div class="banner-info">
			<h3>It is a long established fact that a reader will be distracted by 
			the readable </h3>	
			<div class="search-form">

				<form action="{% url 'home:search' %}" method="GET">
					<input type="text" placeholder="Search..." name="query">
					<input type="submit" value=" " >
				</form>

			</div>		
		</div>	
    </div>
</div>
    <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.1.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/jquery.vide.min.js' %}"></script>

<!--content-->
<div class="content-top ">
	<div class="container ">
		<div class="spec ">
			<h3>Special Offers</h3>
			<div class="ser-t">
				<b></b>
				<span><i></i></span>
				<b class="line"></b>
			</div>
		</div>
			<div class="tab-head ">
				<nav class="nav-sidebar">
					<ul class="nav tabs ">
						{% for spe_subcat in special_subcat %}
					  <li class="{{spe_subcat.status}}"><a href="#{{spe_subcat.slug}}" data-toggle="tab">{{spe_subcat.title}}</a></li>
					  {% endfor %}
					</ul>
				</nav>

				<div class=" tab-content tab-content-t ">
					{% for spe_subcat in special_subcat %}
					<div class="tab-pane {{spe_subcat.status}} text-style" id="{{spe_subcat.slug}}">
						<div class=" con-w3l">
							{% for item in items %}
							{% if spe_subcat.id == item.subcategory_id %}
							<div class="col-md-3 m-wthree">
								<div class="col-m">								
									<a href="#" data-toggle="modal" data-target="#myModal1" class="offer-img">
										<img src="{{item.image.url}}" class="img-responsive" alt="">
										<div class="offer"><p><span>Offer</span></p></div>
									</a>
									<div class="mid-1">
										<div class="women">
											<h6><a href="single.html">{{item.title}}</a></h6>
										</div>
										<div class="mid-2">
											{% if item.discounted_price %}
											<p ><label>${{item.price}}</label><em class="item_price">${{item.discounted_price}}</em></p>
											{% else %}
											<p ><label>${{item.price}}</label></p>
											{% endif%}
											  <div class="block">
												<div class="starbox small ghosting"> </div>
											</div>
											<div class="clearfix"></div>
										</div>
										<div class="add">
											<a href = "{{item.add_to_cat}}"><button class="btn btn-danger my-cart-btn my-cart-b ">Add to Cart</button></a>
										</div>
										
									</div>
								</div>
							</div>
							{% endif %}
							{% endfor %}
							<div class="clearfix"></div>
						 </div>
					</div>
					{% endfor %}
				</div>
			</div>
		
	</div>
	</div>
	</div>

<!--content-->
<div class="content-mid">
	<div class="container">
		{% for one in add_one %}
		<div class="col-md-4 m-w3ls">
			<div class="col-md1 ">
				<a href="kitchen.html">
					<img src="{{one.image}}" class="img-responsive img" alt="">
					<div class="big-sa">
						<h6>New Collections</h6>
						<h3>Season<span>ing </span></h3>
						<p>{{one.description}} </p>
					</div>
				</a>
			</div>
		</div>
		{% endfor %}
		{% for second in add_second %}
		<div class="col-md-4 m-w3ls1">
			<div class="col-md ">
				<a href="hold.html">
					<img src="{{second.image}}" class="img-responsive img" alt="">
					<div class="big-sale">
						<div class="big-sale1">
							<h3>Big <span>Sale</span></h3>
							<p>{{second.description}} </p>
						</div>
					</div>
				</a>
			</div>
		</div>
		{% endfor %}
		<div class="col-md-4 m-w3ls">
			{% for third in add_third %}
			<div class="col-md2 ">
				<a href="kitchen.html">
					<img src="{{third.image}}" class="img-responsive img1" alt="">
					<div class="big-sale2">
						<h3>Cooking <span>Oil</span></h3>
						<p>{{third.description}} </p>
					</div>
				</a>
			</div>
			{% endfor %}
			{% for forth in add_forth %}
			<div class="col-md3 ">
				<a href="hold.html">
					<img src="{{forth.image}}" class="img-responsive img1" alt="">
					<div class="big-sale3">
						<h3>Vegeta<span>bles</span></h3>
						<p>{{forth.description}} </p>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!--content-->
  <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
		  {% for slider in sliders %}
        <li data-target="#myCarousel" data-slide-to="{{slider.rank}}" class="{{slider.status}}"></li>
        {% endfor %}
      </ol>
      <div class="carousel-inner" role="listbox">
		  {% for slider in sliders %}
        <div class="item {{slider.status}}">
         <a href="kitchen.html"> <img class="first-slide" src="{{slider.image}}" alt="{{slider.title}}"></a>
        </div>
        {% endfor %}
      </div>
    
    </div><!-- /.carousel -->

<!--content-->
	<div class="product">
		<div class="container">
			<div class="spec ">
				<h3>Special Offers</h3>
				<div class="ser-t">
					<b></b>
					<span><i></i></span>
					<b class="line"></b>
				</div>
			</div>
				<div class=" con-w3l">
					{% for item in specil_items %}
					<div class="col-md-3 pro-1">
								<div class="col-m">
								<a href="#" data-toggle="modal" data-target="#myModal17" class="offer-img">
										<img src="{{item.image.url}}" class="img-responsive" alt="">
									</a>
									<div class="mid-1">
										<div class="women">
											<h6><a href="{{item.get_item_url}}">{{item.title}}</a></h6>
										</div>
										<div class="mid-2">
											{% if  item.discounted_price %}
											<p ><label>Rs.{{item.price}}</label><em class="item_price">Rs.{{item.discounted_price}}</em></p>
											{% else %}
											<p ><em class="item_price">Rs.{{item.price}}</em></p>
											{% endif %}
											  <div class="block">
												<div class="starbox small ghosting"> </div>
											</div>
											<div class="clearfix"></div>
										</div>
											<div class="add add-2">
										   <button class="btn btn-danger my-cart-btn my-cart-b" data-id="1" data-name="product 1" data-summary="summary 1" data-price="6.00" data-quantity="1" data-image="images/of16.png">Add to Cart</button>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
							<div class="clearfix"></div>
						 </div>
		</div>
	</div>
{% endblock %}

ecommerce-master/ecommerce-master/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <!--banner-->
<div class="banner-top">
	<div class="container">
		<h3 >Register</h3>
		<h4><a href="index.html">Home</a><label>/</label>Register</h4>
		<div class="clearfix"> </div>
	</div>
</div>

<!--login-->

	<div class="login">
		<div class="main-agileits">
				<div class="form-w3agile form1">
					<h3>Register</h3>

					<form  method="POST">
						{% csrf_token %}
						{% for message in messages %}
						<center><fornt color = 'red'>{{message}}</fornt></center>
						{% endfor%}
						<div class="key">
							<i class="fa fa-user" aria-hidden="true"></i>
							<input  type="text"  name="username" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Username';}" required="">
							<div class="clearfix"></div>
						</div>
						<div class="key">
							<i class="fa fa-envelope" aria-hidden="true"></i>
							<input  type="text" name="email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
							<div class="clearfix"></div>
						</div>
						<div class="key">
							<i class="fa fa-lock" aria-hidden="true"></i>
							<input  type="password" name="password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}" required="">
							<div class="clearfix"></div>
						</div>
						<div class="key">
							<i class="fa fa-lock" aria-hidden="true"></i>
							<input  type="password" name="confirm Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Confirm Password';}" required="">
							<div class="clearfix"></div>
						</div>
						<input type="submit" value="Submit">
					</form>
				</div>
				
			</div>
		</div>
{% endblock %}

ecommerce-master/ecommerce-master/templates/search_product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--content-->
		<div class="product">
		<div class="container">
			<div class="spec ">
				<h3>Search Products</h3>
				<div class="ser-t">
					<b></b>
					<span><i></i></span>
					<b class="line"></b>
				</div>
			</div>
				<div class=" con-w3l agileinf">
					{% for search in search_query %}
							<div class="col-md-3 pro-1">
								<div class="col-m">
								<a href="#" data-toggle="modal" data-target="#{{search.slug}}" class="offer-img">
										<img src="{{search.image}}" class="img-responsive" alt="">
								</a>
									<div class="modal fade" id="{{search.slug}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				<div class="modal-dialog" role="document">
					<div class="modal-content modal-info">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						</div>
						<div class="modal-body modal-spa">
								<div class="col-md-5 span-2">
											<div class="item">
												<img src="{{search.image}}" class="img-responsive" alt="">
											</div>
								</div>
								<div class="col-md-7 span-1 ">
									<h3>{{search.title}}</h3>
									<p class="in-para"> {{search.stock}}</p>
									<div class="price_single">
										{% if search.discounted_price %}
									  <span class="reducedfrom "><del>${{search.price}}</del>${{search.discounted_price}}</span>
												{% else %}
										<span class="reducedfrom ">${{search.price}}</span>
										{% endif %}
									 <div class="clearfix"></div>
									</div>
									<h4 class="quick">Quick Overview:</h4>
									<p class="quick_desc"> {{search.description}} </p>
									 <div class="add-to">
										   <button class="btn btn-danger my-cart-btn my-cart-btn1 " data-id="2" data-name="Sunflower Oil" data-summary="summary 2" data-price="9.00" data-quantity="1" data-image="images/of1.png">Add to Cart</button>
										</div>
								</div>
								<div class="clearfix"> </div>
							</div>
						</div>
					</div>
				</div>
<!--									Product information-->
									<div class="mid-1">
										<div class="women">
											<h6><a href="{{search.get_item_url}}">{{ search.title }}</a></h6>
										</div>
										<div class="mid-2">
											{% if search.discounted_price %}
											<p ><label>${{search.price}}</label><em class="item_price">${{search.discounted_price}}</em></p>
											{% else %}
											<p ><em class="item_price">${{search.price}}</em></p>
											{% endif %}
											  <div class="block">
												<div class="starbox small ghosting"> </div>
											</div>
											<div class="clearfix"></div>
										</div>
											<div class="add">
										   <button class="btn btn-danger my-cart-btn my-cart-b" data-id="24" data-name="Wheat" data-summary="summary 24" data-price="6.00" data-quantity="1" data-image="images/of24.png">Add to Cart</button>
										</div>
									</div>
								</div>
							</div>

						{% endfor %}

							<div class="clearfix"></div>
						 </div>
		</div>
	</div>
{% endblock %}

ecommerce-master/ecommerce-master/templates/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <!--banner-->
<div class="banner-top">
	<div class="container">
		<h3 >Lorem</h3>
		<h4><a href="index.html">Home</a><label>/</label>Lorem</h4>
		<div class="clearfix"> </div>
	</div>
</div>
		<div class="single">
			<div class="container">
						<div class="single-top-main">
	   		<div class="col-md-5 single-top">
	   		<div class="single-w3agile">

<div id="picture-frame">
			<img src="../{{object.image.url}}" data-src="../{{object.image.url}}" alt="" class="img-responsive"/>
		</div>
										<script src="{% static 'js/jquery.zoomtoo.js' %}"></script>
								<script>
			$(function() {
				$("#picture-frame").zoomToo({
					magnify: 1
				});
			});
		</script>



			</div>
			</div>
			<div class="col-md-7 single-top-left ">
								<div class="single-right">
				<h3>{{object.title}}</h3>


				 <div class="pr-single">
				  <p class="reduced "><del>$10.00</del>$5.00</p>
				</div>
				<div class="block block-w3">
					<div class="starbox small ghosting"> </div>
				</div>
				<p class="in-pa"> {{object.description}}</p>

				<ul class="social-top">
					<li><a href="#" class="icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i><span></span></a></li>
					<li><a href="#" class="icon dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i><span></span></a></li>
				</ul>
					<div class="add add-3">
										   <button class="btn btn-danger my-cart-btn my-cart-b" data-id="1" data-name="Wheat" data-summary="summary 1" data-price="6.00" data-quantity="1" data-image="images/si.jpg">Add to Cart</button>
										</div>



			<div class="clearfix"> </div>
			</div>


			</div>
		   <div class="clearfix"> </div>
	   </div>


	</div>
</div>


{% endblock %}